# Generated by Django 4.2.7 on 2024-02-05 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_rename_online_room_members_room_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(blank=True, related_name="rooms", to=settings.AUTH_USER_MODEL),
        ),
    ]
