# Generated by Django 4.2.7 on 2024-02-05 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_room_members"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="admin",
            new_name="user",
        ),
    ]
